name: Update Corona Charts DE

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  schedule:
    - cron: "*/45 5-21/2 * * 1-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bots/corona-charts-de/
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./bots/corona-charts-de/requirements.txt') }}
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python scripts
        run: |
          python rki_vaccinations_daily/rki_vaccinations_daily.py
          python rki_vaccinations_herd_immunity/rki_vaccinations_herd_immunity_age.py
          python rki_vaccinations_states/rki_vaccinations_states.py
          python rki_vaccinations_states/rki_vaccinations_type.py
          python rki_age_groups/rki_hospitalizations.py
          python rki_age_groups/rki_incidence.py
          python rki_notbremse/rki_notbremse.py
          python rki_2g/rki_2g.py
          python rki_tests/rki_tests.py
          python rki_cases/divi_icu.py
          python rki_cases/divi_icu_map.py
          python rki_cases/rki_cases_map.py
          python rki_cases/rki_deaths.py
          python rki_cases/rki_cases.py
          python rki_cases/rki_index.py
          python rki_cases/rki_dashboard.py
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install node packages
        run: npm install -g @nzz/q-cli
      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_DE_SLACK }}
