name: Corona Widget Test R (shu)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bots/coronawidgettest/
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.0.5"
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/R/renv
          key: ${{ runner.os }}-r-4.0.5-renv-${{ hashFiles('./bots/corona-charts/renv.lock') }}
      - name: Restore R packages
        run: |
          install.packages("renv")
          renv::activate()
          renv::restore()
        shell: Rscript {0}
      - name: Run R scripts
        run: |
          Rscript src/main.R
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install node packages
        run: npm install -g @nzz/q-cli
      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
          Q_STAGING_SERVER: ${{ secrets.Q_STAGING_SERVER }}
          Q_STAGING_ACCESSTOKEN: ${{ secrets.Q_STAGING_ACCESSTOKEN }}
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
