name: Credit Suisse Charts

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  # At minute 0 and 30 past every hour from 8 through 19 on every day-of-week from Monday through Friday.
  schedule:
    - cron: "40,30 8-19 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./bots/credit_suisse/
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >>$GITHUB_OUTPUT
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./bots/credit_suisse/requirements.txt') }}
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python scripts
        run: |
          python credit_suisse.py
          git pull
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: :!*.json
          commit_message: Upload csvs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install node packages
        run: npm install -g @nzz/q-cli
      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
         status: ${{ job.status }}
         notify_when: "failure"
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
