name: Update EU-Corona-Inzidenzkarte

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  # This will run it on 12:10 MEZ every day (11:10 GMT)
  schedule:
    - cron: "10 11 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bots/eu-corona-inzidenz/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run update
        env:
          Q_PRODUCTION_SERVER: https://q-server.st.nzz.ch/
          Q_PRODUCTION_USERNAME: ${{ secrets.Q_PRODUCTION_USERNAME }}
          Q_PRODUCTION_PASSWORD: ${{ secrets.Q_PRODUCTION_PASSWORD }}
