name: Log Failure Test

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  # This will run at minute 0 and 30 past every hour from 7 through 19 CEST (5 - 17 GMT)
  schedule:
    - cron: "0,30 5-17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
      - name: Fail on purpose
        run: exit 1
