name: [Deaktiviert] Update Monkeypox Charts

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  schedule:
    - cron: "0 6,15 * * *"

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bots/monkeypox-charts/
    steps:
      - uses: actions/checkout@v2
#      - name: Setup R
#        uses: r-lib/actions/setup-r@v1
#        with:
#          r-version: "4.0.5"
#      - name: Install system dependencies
#        run: |
#          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
#      - name: Cache R packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.cache/R/renv
#          key: ${{ runner.os }}-r-4.0.5-renv-${{ hashFiles('./bots/stock-market/renv.lock') }}
#      - name: Restore R packages
#        run: |
#          install.packages("renv")
#          renv::activate()
#          renv::restore()
#        shell: Rscript {0}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache python packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./bots/monkeypox-charts/requirements.txt') }} # path should be ok
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python scripts
        run: | # 
          python monkeypox_auto_int_20220726.py
      # - uses: stefanzweifel/git-auto-commit-action@v4 # <---- ?
      #   with:
      #     commit_message: update monkeypox charts #
      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install node packages
        run: npm install -g @nzz/q-cli
      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
