name: Update Strom Charts CH

on:
  # Set to run at 6 am every Monday
  schedule: 
    - cron: "0 4 * * *"

  workflow_dispatch:

env:
  LANG: "de_DE.UTF-8"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bots/strom-charts-ch/
    steps:
      - uses: actions/checkout@v3
      - name: de_DE.UTF-8
        run: |
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >>$GITHUB_OUTPUT
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./bots/monkeypox-charts/requirements.txt') }} # path should be ok
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python scripts
        run: |  
          python main.py
          python stromverbrauch.py
          git pull
      #- uses: stefanzweifel/git-auto-commit-action@v4
       # with:
        #  file_pattern: :!*.json
         # commit_message: Upload swiss energy data
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install node packages
        run: npm install -g @nzz/q-cli
      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
