name: Update Verivox Data DE

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  schedule:
    - cron: "10 5-7 * * 1-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bots/verivox-de/
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install node packages
        run: |
          npm install -g @nzz/q-cli
          npm install -g mapshaper
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache python packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./bots/verivox-de/requirements.txt') }}
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python scripts
        run: |
          python agsi-gas-storage.py
          python verivox-daily.py
        env:
          VERIVOX_USERNAME: ${{ secrets.VERIVOX_USERNAME }}
          VERIVOX_PASSWORD: ${{ secrets.VERIVOX_PASSWORD }}
      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
      - name: Cleanup
        run: rm -f ./data/de-postcode-geographic-1-5.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ./data/gas-strom-bundesschnitt.tsv
          commit_message: Update Verivox data
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_DE_SLACK }}
